logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 101.35.51.125 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初始等待时长
          multiplier: 1 # 下次失败等待时长的倍数
          max-attempts: 3 # 最大重试次数
          stateless: true # 无状态，如果业务中包含事务，则更改为有状态